version: 2.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Installing GCC and MAKE
          command: apt-get update && apt-get install -y gcc make
      - run:
          name: Building Tests
          command: make test.exe
      - run:
          name: Running Tests
          command: ./test.exe
